#
#==================================================================================
#   Copyright (c) 2019 AT&T Intellectual Property.
#   Copyright (c) 2019 Nokia
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#==================================================================================
#
#
#   Abstract:           Configuration values for the routing manager
#   Date:               29 May 2019
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ricplt-rtmgr-rtmgrcfg
data:
  # FQDN and port info of the platform components for routing manager to form
  # and distribute corresponding routes to them
  rtmgrcfg: |
       "PlatformComponents":
         -
           "name": "SUBMAN"
           "fqdn": "service-ricplt-submgr-rmr.ricplt"
           "port": 4560
         -
           "name": "E2MAN"
           "fqdn": "10.0.2.15"
           "port": 3801
         -
           "name": "RSM"
           "fqdn": "service-ricplt-rsm-rmr.ricplt"
           "port": 4801
         -
           "name": "A1MEDIATOR"
           "fqdn": "service-ricplt-a1mediator-rmr.ricplt"
           "port": 4562
       "XMURL":
         "http://service-ricplt-appmgr-http:8080/ric/v1/xapps"
       "E2MURL":
         "http://10.0.2.15:3800/v1/e2t/list"
       "RTFILE":
         "/db/rt.json"
       "CFGFILE":
         "/cfg/rtmgr-config.yaml"
       "RPE":
         "rmrpush"
       "SBI":
         "rmrpush"
       "SBIURL":
         "0.0.0.0"
       "NBI":
         "httpRESTful"
       "NBIURL":
         "http://10.0.2.15:31000"
       "SDL":
         "file"
       "local":
         "host": ":8080"
       "logger":
         "level": 4
       "rmr":
         "protPort": "tcp:31500"
         "maxSize": 1024
         "numWorkers": 1
         "threadType": 1
       "messagetypes": [
          "RIC_HEALTH_CHECK_REQ=100",
          "RIC_HEALTH_CHECK_RESP=101",
          "RIC_ALARM=110",
          "RIC_ALARM_QUERY=111",
          "RIC_SCTP_CONNECTION_FAILURE=1080",
          "E2_TERM_INIT=1100",
          "E2_TERM_KEEP_ALIVE_REQ=1101",
          "E2_TERM_KEEP_ALIVE_RESP=1102",
          "RIC_SCTP_CLEAR_ALL=1090",
          "RAN_CONNECTED=1200",
          "RAN_RESTARTED=1210",
          "RAN_RECONFIGURED=1220",
          "RIC_ENB_LOAD_INFORMATION=10020",
          "RIC_X2_SETUP_REQ=10060",
          "RIC_X2_SETUP_RESP=10061",
          "RIC_X2_SETUP_FAILURE=10062",
          "RIC_X2_RESET=10070",
          "RIC_X2_RESET_RESP=10071",
          "RIC_ENB_CONF_UPDATE=10080",
          "RIC_ENB_CONF_UPDATE_ACK=10081",
          "RIC_ENB_CONF_UPDATE_FAILURE=10082",
          "RIC_RES_STATUS_REQ=10090",
          "RIC_RES_STATUS_RESP=10091",
          "RIC_RES_STATUS_FAILURE=10092",
          "RIC_ENDC_X2_SETUP_REQ=10360",
          "RIC_ENDC_X2_SETUP_RESP=10361",
          "RIC_ENDC_X2_SETUP_FAILURE=10362",
          "RIC_ENDC_CONF_UPDATE=10370",
          "RIC_ENDC_CONF_UPDATE_ACK=10371",
          "RIC_ENDC_CONF_UPDATE_FAILURE=10372",
          "RIC_E2_SETUP_REQ=12001",
          "RIC_E2_SETUP_RESP=12002",
          "RIC_E2_SETUP_FAILURE=12003",
          "RIC_ERROR_INDICATION=12007",
          "RIC_SUB_REQ=12010",
          "RIC_SUB_RESP=12011",
          "RIC_SUB_FAILURE=12012",
          "RIC_SUB_DEL_REQ=12020",
          "RIC_SUB_DEL_RESP=12021",
          "RIC_SUB_DEL_FAILURE=12022",
          "A1_POLICY_REQ=20010",
          "A1_POLICY_RESP=20011",
          "A1_POLICY_QUERY=20012",
          "TS_UE_LIST=30000",
          "TS_QOE_PRED_REQ=30001",
          "TS_QOE_PREDICTION=30002",
          "MC_REPORT=30010",
          "DCAPTERM_RTPM_RMR_MSGTYPE=33001",
          "DCAPTERM_GEO_RMR_MSGTYPE=33002",
          "RIC_SERVICE_QUERY=12060",
          ]
       "PlatformRoutes": [
         { 'messagetype': 'RIC_SUB_REQ', 'senderendpoint': 'SUBMAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_SUB_DEL_REQ', 'senderendpoint': 'SUBMAN', 'subscriptionid': -1,'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_SUB_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'SUBMAN', 'meid': ''},
         { 'messagetype': 'RIC_SUB_DEL_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'SUBMAN', 'meid': ''},
         { 'messagetype': 'RIC_SUB_FAILURE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'SUBMAN', 'meid': ''},
         { 'messagetype': 'RIC_SUB_DEL_FAILURE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'SUBMAN', 'meid': ''},
         { 'messagetype': 'RIC_X2_SETUP_REQ', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_X2_RESET', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_X2_RESET_RESP', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_ENDC_X2_SETUP_REQ', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_ENB_CONF_UPDATE_ACK', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_ENB_CONF_UPDATE_FAILURE', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_ENDC_CONF_UPDATE_ACK', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_ENDC_CONF_UPDATE_FAILURE', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_E2_SETUP_REQ', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'E2_TERM_INIT', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_X2_SETUP_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_X2_SETUP_FAILURE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_X2_RESET', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_X2_RESET_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_ENDC_X2_SETUP_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_ENDC_X2_SETUP_FAILURE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_ENDC_CONF_UPDATE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_SCTP_CONNECTION_FAILURE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_ERROR_INDICATION', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_ENB_CONF_UPDATE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RIC_ENB_LOAD_INFORMATION', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'E2_TERM_KEEP_ALIVE_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'E2MAN', 'meid': ''},
         { 'messagetype': 'RAN_CONNECTED', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': 'RSM', 'meid': ''},
         { 'messagetype': 'RAN_RESTARTED', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': 'RSM', 'meid': ''},
         { 'messagetype': 'RAN_RECONFIGURED', 'senderendpoint': 'E2MAN', 'subscriptionid': -1, 'endpoint': 'RSM', 'meid': ''},
         { 'messagetype': 'RIC_RES_STATUS_REQ', 'senderendpoint': 'RSM', 'subscriptionid': -1, 'endpoint': '', 'meid': '%meid'},
         { 'messagetype': 'RIC_RES_STATUS_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'RSM', 'meid': ''},
         { 'messagetype': 'RIC_RES_STATUS_FAILURE', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'RSM', 'meid': ''},
         { 'messagetype': 'A1_POLICY_QUERY', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'A1MEDIATOR', 'meid': ''},
         { 'messagetype': 'A1_POLICY_RESP', 'senderendpoint': '', 'subscriptionid': -1, 'endpoint': 'A1MEDIATOR', 'meid': ''},
          ]

